### ISSUE TITLE
ログイン済みユーザーの処理

### ISSUE THREAD

**Issue by aoilo** [same0216/booth_summary_front#1]
把握してると思いますが
ログイン済みユーザーがログイン画面呼び出した時はトップページにリダイレクトさせる様にお願いしますね😌

https://github.com/same0216/booth_summary_front/blob/27df2930039d637e01063b251b2d08959d353b94/app/login/page.tsx#L16

**Comment by same0216** [comment]
ログイン済の場合トップページにリダイレクトさせるように処理追加。

ついでにルートにアクセスしたらログイン画面にリダイレクトさせる処理を設定ファイル側に移しました。
